version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  exclusions:
    paths:
      - examples*
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/qeeqez/work-email-validator
  exclusions:
    paths:
      - examples*

