version: "2"
linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - depguard
    - gochecknoglobals
    - nlreturn
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - wsl # Deprecated
  exclusions:
    paths:
      - example*