version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - wsl
    - depguard
    - gochecknoglobals
  exclusions:
    paths:
      - example*
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/qeeqez/work-email-validator
  exclusions:
    paths:
      - example*

